name: Release

on:
  push:
    branches:
      - main
jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' # It will run install dependencies just if hash of yarn.lock changed
        run: yarn install --frozen-lockfile --prefer-offline
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Restore node_modules
        uses: actions/cache@v3
        id: restore-build
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Restore jest cache
        uses: actions/cache@v3
        with:
          path: .jest-cache
          key: ${{ runner.os }}-${{ hashFiles('**/.jest-cache/**') }}

      - name: Run tests
        run: yarn test

  build:
    name: Test build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Restore node_modules
        uses: actions/cache@v3
        id: restore-build
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Run build
        run: yarn build

  deadcode:
    name: Find dead code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Restore node_modules
        uses: actions/cache@v3
        id: restore-build
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Find dead code
        run: yarn deadCode

  release:
    name: Release version
    runs-on: ubuntu-latest
    needs: [test, build, deadcode]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          registry-url: 'https://registry.npmjs.org'
          scope: '@michael1997'

      - name: Restore node_modules
        uses: actions/cache@v3
        id: restore-build
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Publish Version
        run: yarn publish:public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Tag release
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
